version: "3.9"
services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos
    env_file:
      - ../env/nacos-standalone-mariadb.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      - mysql
    restart: on-failure:3
  mysql:
    container_name: mariadb
    build:
      context: ./image/mariadb/10/
    image: nacos/mariadb:10
    env_file:
      - ../env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

