version: "3.9"
services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos
    env_file:
      - ../env/nacos-standalone-mariadb.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure:3
  mysql:
    container_name: mariadb
    build:
      context: ./image/mariadb/10/
    image: nacos/mariadb:10
    env_file:
      - ../env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SHOW DATABASES"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped

